version: "3.9"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: fitt-backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./Backend:/app
    restart: always

  frontend:
    build:
      context: ./Frontend
    container_name: fitt-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
